import React, { useEffect, useRef, useState } from 'react';
import { GameAudio } from '../game/audio';
import { getRandomWordForWave } from '../game/words';
import GameHUD from './GameHUD';

export default function GameCanvas({
  username,
  shipColor,
  isMultiplayer,
  roomCode,
  players,
  socket,
  onGameOver,
  onScoreUpdate
}) {
  const canvasRef = useRef(null);
  const stateRef = useRef({
    score: 0,
    multiplier: 1,
    wave: 1,
    health: 100,
    streak: 0,
    enemies: [],
    bullets: [],
    particles: [],
    lasers: [],
    scenery: [],
    nebulaColor: { h: 260, s: 50, l: 10 },
    targetNebulaColor: { h: 260, s: 50, l: 10 },
    activeWordId: null,
    screenShake: 0,
    flashFrame: 0,
    waveTransitionTimer: 180, // Countdown frames for wave intro
    waveState: 'intro', // 'intro', 'playing', 'boss_warning', 'boss_fight', 'victory'
    bossObj: null,
    lastSpawnTime: 0,
    waveSpawnedCount: 0,
    waveTotalToSpawn: 10,
    isLocalGameOver: false,
    teammates: []
  });

  const [hudState, setHudState] = useState({
    score: 0,
    multiplier: 1,
    wave: 1,
    health: 100,
    teammates: []
  });

  // Track keydown handler to remove on unmount
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    // Set canvas dimensions
    const resizeCanvas = () => {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
      
      // Initialize scenery if empty
      if (stateRef.current.scenery.length === 0) {
        initScenery(canvas.width, canvas.height);
      }
    };
    
    resizeCanvas();
    window.addEventListener('resize', resizeCanvas);

    // Focus canvas
    canvas.focus();

    // Start Game loop
    let animationFrameId;
    const render = () => {
      updateGame();
      drawGame();
      animationFrameId = requestAnimationFrame(render);
    };
    render();

    // Start background music
    GameAudio.playMusic('endure');

    return () => {
      window.removeEventListener('resize', resizeCanvas);
      cancelAnimationFrame(animationFrameId);
      GameAudio.stopMusic();
    };
  }, []);

  // Sync teammates from props
  useEffect(() => {
    if (isMultiplayer && players) {
      const state = stateRef.current;
      // Filter out local player and store others as teammates
      const local = players.find(p => p.socketId === socket?.id);
      const mates = players.map(p => {
        // Find if they already have health in our state
        const existingMate = state.teammates.find(m => m.socketId === p.socketId);
        return {
          socketId: p.socketId,
          username: p.username,
          color: p.color,
          position: p.position,
          isHost: p.isHost,
          score: p.score || 0,
          level: p.level || 1,
          health: existingMate ? existingMate.health : 100
        };
      });
      state.teammates = mates;
      
      // If we are playing, find our current health
      const meInState = mates.find(m => m.socketId === socket?.id);
      if (meInState) {
        state.health = meInState.health;
      }

      setHudState(prev => ({
        ...prev,
        teammates: mates
      }));
    }
  }, [players, isMultiplayer, socket]);

  // Handle incoming Socket messages during gameplay
  useEffect(() => {
    if (!isMultiplayer || !socket) return;

    const handleMessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        const state = stateRef.current;

        switch (data.type) {
          case 'ROOM_PLAYERS_UPDATE': {
            // Handled via players prop sync, but keeping fallback
            break;
          }

          case 'SPAWN_ENEMIES': {
            // Add enemies generated by host
            if (socket.id !== data.hostId) {
              data.enemies.forEach(e => {
                state.enemies.push({
                  ...e,
                  y: -40 // start offscreen
                });
              });
            }
            break;
          }

          case 'TYPING_STRIKE': {
            // Render teammate shot
            const mate = state.teammates.find(m => m.socketId === data.playerId);
            const targetEnemy = state.enemies.find(e => e.id === data.wordId);
            
            if (mate && targetEnemy) {
              const shipX = getShipX(mate.position, window.innerWidth);
              const shipY = window.innerHeight - 80;
              
              // Add laser beam
              state.lasers.push({
                fromX: shipX,
                fromY: shipY - 20,
                toX: data.x,
                toY: data.y,
                color: `var(--neon-${mate.color})`,
                alpha: 1.0
              });

              // Subtract character on target enemy
              targetEnemy.targetIndex = data.charIndex + 1;
              
              // Particle burst at impact
              createExplosion(data.x, data.y, `var(--neon-${mate.color})`, 8);

              // Play strike audio
              GameAudio.play('hit');

              if (data.wordFinished) {
                // Enemy dies
                state.enemies = state.enemies.filter(e => e.id !== data.wordId);
                handleEnemyCompletion(data.wordId);
                createExplosion(data.x, data.y, `var(--neon-${mate.color})`, 25, true);
                GameAudio.play('explosion');
                
                // Update teammate's score locally for drawing
                mate.score += data.damage;
              }
            }
            break;
          }

          case 'CANCEL_BULLET': {
            // Find and destroy bullet
            const bullet = state.bullets.find(b => b.id === data.bulletId);
            if (bullet) {
              createExplosion(bullet.x, bullet.y, '#fff', 12);
              state.bullets = state.bullets.filter(b => b.id !== data.bulletId);
              GameAudio.play('hit');
            }
            break;
          }

          case 'SPAWN_BULLET': {
            if (socket.id !== data.hostId) {
              state.bullets.push(data.bullet);
            }
            break;
          }

          case 'SYNC_BOSS_PHASE': {
            // Start boss fight phase on clients
            state.waveState = 'boss_fight';
            state.bossObj = {
              id: 'boss',
              x: window.innerWidth / 2,
              y: 120,
              width: 180,
              height: 100,
              health: 100,
              maxHealth: 100,
              words: data.bossWords || [],
              phase: data.phase,
              shootTimer: 120
            };
            break;
          }

          case 'PLAYER_HIT': {
            const mate = state.teammates.find(m => m.socketId === data.playerId);
            if (mate) {
              mate.health = data.health;
              if (mate.socketId === socket.id) {
                state.health = data.health;
                state.screenShake = 15;
                state.flashFrame = 6;
                GameAudio.play('explosionPlayer');
              }
            }
            break;
          }

          case 'GAME_OVER': {
            triggerGameOver(data.finalScore, data.waveReached);
            break;
          }

          case 'NEXT_WAVE': {
            state.wave = data.wave;
            state.waveState = 'intro';
            state.waveTransitionTimer = 180;
            state.enemies = [];
            state.bullets = [];
            state.waveSpawnedCount = 0;
            state.waveTotalToSpawn = 10 + data.wave * 4;
            // Shift target nebula colors
            state.targetNebulaColor = {
              h: (260 + data.wave * 30) % 360,
              s: 60,
              l: 8 + (data.wave % 4)
            };
            break;
          }
        }
      } catch (e) {
        console.error('Multiplayer message parse error:', e);
      }
    };

    socket.addEventListener('message', handleMessage);
    return () => {
      socket.removeEventListener('message', handleMessage);
    };
  }, [isMultiplayer, socket]);

  // Initial scenery population
  const initScenery = (width, height) => {
    const scenery = [];
    const count = 25;
    
    for (let i = 0; i < count; i++) {
      // Left side (0% to 20%) or Right side (80% to 100%)
      const isLeft = Math.random() < 0.5;
      const x = isLeft 
        ? Math.random() * (width * 0.18) 
        : width - Math.random() * (width * 0.18);
      const y = Math.random() * height;
      const size = 15 + Math.random() * 40;
      const type = Math.random() < 0.3 ? 'tower' : Math.random() < 0.7 ? 'asteroid' : 'planet';
      const speedMultiplier = 0.2 + Math.random() * 0.4;
      const rotation = Math.random() * Math.PI * 2;
      const rotationSpeed = (Math.random() - 0.5) * 0.01;
      const color = `hsla(${200 + Math.random() * 80}, 30%, 40%, 0.15)`;

      scenery.push({ x, y, size, type, speedMultiplier, rotation, rotationSpeed, color });
    }
    stateRef.current.scenery = scenery;
  };

  // Helper to determine Ship center X coordinate based on lobby index
  const getShipX = (position, screenWidth) => {
    if (position === 'left') return screenWidth * 0.25;
    if (position === 'right') return screenWidth * 0.75;
    return screenWidth / 2; // host/center
  };

  const createExplosion = (x, y, color, particleCount = 15, isBig = false) => {
    const state = stateRef.current;
    const count = isBig ? particleCount * 2 : particleCount;
    
    for (let i = 0; i < count; i++) {
      const angle = Math.random() * Math.PI * 2;
      const speed = (isBig ? 2 : 1) + Math.random() * (isBig ? 6 : 4);
      state.particles.push({
        x,
        y,
        vx: Math.cos(angle) * speed,
        vy: Math.sin(angle) * speed,
        size: (isBig ? 2 : 1) + Math.random() * 3,
        color,
        alpha: 1.0,
        life: 30 + Math.random() * 30
      });
    }
  };

  // Keyboard Event Handlers
  const handleKeyDown = (e) => {
    const state = stateRef.current;
    if (state.isLocalGameOver) return;

    const key = e.key;
    if (key.length !== 1) return; // Ignore modifier keys (Shift, Ctrl, etc.)

    const char = key.toLowerCase();
    
    // Check if we are typing letters on single-character bullets (white)
    // Anyone can type/cancel bullets in co-op!
    const bulletToHitIndex = state.bullets.findIndex(b => b.letter.toLowerCase() === char);
    if (bulletToHitIndex !== -1) {
      const bullet = state.bullets[bulletToHitIndex];
      // Cancel it locally
      state.bullets.splice(bulletToHitIndex, 1);
      createExplosion(bullet.x, bullet.y, '#ffffff', 10);
      GameAudio.play('hit');
      
      // Update score locally
      state.score += 10;
      stateRef.current.score = state.score;
      setHudState(prev => ({ ...prev, score: state.score }));
      onScoreUpdate(state.score, state.wave);
      
      if (isMultiplayer && socket) {
        socket.send(JSON.stringify({
          type: 'CANCEL_BULLET',
          bulletId: bullet.id
        }));
        
        socket.send(JSON.stringify({
          type: 'UPDATE_SCORE',
          score: state.score,
          level: state.wave
        }));
      }
      return;
    }

    // Standard word typing
    if (state.activeWordId !== null) {
      // We have an active target
      const enemy = state.enemies.find(e => e.id === state.activeWordId);
      if (enemy) {
        const nextChar = enemy.word[enemy.targetIndex].toLowerCase();
        if (char === nextChar) {
          hitTarget(enemy);
        } else {
          // Miss resets streak & multiplier
          state.streak = 0;
          state.multiplier = 1;
          setHudState(prev => ({ ...prev, multiplier: 1 }));
        }
      } else {
        // Targeted enemy was destroyed by teammate or went offscreen
        state.activeWordId = null;
        tryAcquireNewTarget(char);
      }
    } else {
      // Try to acquire a new target starting with the typed letter
      tryAcquireNewTarget(char);
    }
  };

  const tryAcquireNewTarget = (char) => {
    const state = stateRef.current;
    
    // Find enemies whose current letter matches the typed character
    // In co-op, we can ONLY target enemies that match our ship color!
    const eligibleEnemies = state.enemies.filter(e => {
      const matchesColor = !isMultiplayer || e.color === shipColor;
      const startsWithChar = e.word[0].toLowerCase() === char;
      return matchesColor && startsWithChar && e.targetIndex === 0;
    });

    if (eligibleEnemies.length === 0) return;

    // Pick the enemy closest to the bottom
    eligibleEnemies.sort((a, b) => b.y - a.y);
    const target = eligibleEnemies[0];
    state.activeWordId = target.id;
    GameAudio.play('target');
    hitTarget(target);
  };

  const hitTarget = (enemy) => {
    const state = stateRef.current;
    const canvas = canvasRef.current;
    if (!canvas) return;

    const charIndex = enemy.targetIndex;
    enemy.targetIndex += 1;
    
    // Increment streak/multiplier
    state.streak += 1;
    if (state.streak % 10 === 0 && state.multiplier < 5) {
      state.multiplier += 1;
      setHudState(prev => ({ ...prev, multiplier: state.multiplier }));
      
      // Play multiplier audio
      if (state.multiplier === 2) GameAudio.play('multi2');
      if (state.multiplier >= 3) GameAudio.play('multi3');
    }

    // Add laser beam from local player ship
    const localPosition = isMultiplayer 
      ? players.find(p => p.socketId === socket?.id)?.position || 'center' 
      : 'center';
    const shipX = getShipX(localPosition, canvas.width);
    const shipY = canvas.height - 80;

    const charOffset = charIndex * 14; // Font spacing approximation
    const wordWidth = enemy.word.length * 14;
    const startX = enemy.x - wordWidth / 2;
    const letterX = startX + charOffset + 7;
    const letterY = enemy.y;

    state.lasers.push({
      fromX: shipX,
      fromY: shipY - 20,
      toX: letterX,
      toY: letterY,
      color: `var(--neon-${shipColor})`,
      alpha: 1.0
    });

    // Spark particles at impact point
    createExplosion(letterX, letterY, `var(--neon-${shipColor})`, 8);
    GameAudio.play('plasma');

    // Check if word completed
    const wordFinished = enemy.targetIndex >= enemy.word.length;
    let scoreGained = 10 * state.multiplier;

    if (wordFinished) {
      // Calculate completion score bonus
      scoreGained += enemy.word.length * 5 * state.multiplier;
      state.activeWordId = null;
      
      // Explosion effect
      createExplosion(enemy.x, enemy.y, `var(--neon-${enemy.color})`, 22, true);
      GameAudio.play('explosion');
      
      // Remove enemy from list
      state.enemies = state.enemies.filter(e => e.id !== enemy.id);
      handleEnemyCompletion(enemy.id);
    }

    state.score += scoreGained;
    stateRef.current.score = state.score;
    setHudState(prev => ({ ...prev, score: state.score }));
    onScoreUpdate(state.score, state.wave);

    // Sync typing action to other players
    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'TYPING_STRIKE',
        wordId: enemy.id,
        charIndex: charIndex,
        damage: scoreGained,
        x: letterX,
        y: letterY,
        wordFinished: wordFinished
      }));

      socket.send(JSON.stringify({
        type: 'UPDATE_SCORE',
        score: state.score,
        level: state.wave
      }));
    }
  };

  // Game Logic Tick
  const updateGame = () => {
    const state = stateRef.current;
    const canvas = canvasRef.current;
    if (!canvas || state.isLocalGameOver) return;

    // Shift background nebula colors smoothly
    state.nebulaColor.h += (state.targetNebulaColor.h - state.nebulaColor.h) * 0.01;
    state.nebulaColor.s += (state.targetNebulaColor.s - state.nebulaColor.s) * 0.01;
    state.nebulaColor.l += (state.targetNebulaColor.l - state.nebulaColor.l) * 0.01;

    // Tick down visual effects
    if (state.screenShake > 0) state.screenShake *= 0.9;
    if (state.flashFrame > 0) state.flashFrame -= 1;

    // Scroll scenery
    state.scenery.forEach(item => {
      item.y += item.speedMultiplier * (1 + state.wave * 0.08);
      item.rotation += item.rotationSpeed;
      if (item.y > canvas.height + item.size) {
        // Wrap to top and randomize horizontal position
        item.y = -item.size;
        const isLeft = Math.random() < 0.5;
        item.x = isLeft 
          ? Math.random() * (canvas.width * 0.18) 
          : canvas.width - Math.random() * (canvas.width * 0.18);
        item.rotation = Math.random() * Math.PI * 2;
      }
    });

    // Laser fading
    state.lasers.forEach(laser => {
      laser.alpha -= 0.1;
    });
    state.lasers = state.lasers.filter(laser => laser.alpha > 0);

    // Particles physics
    state.particles.forEach(p => {
      p.x += p.vx;
      p.y += p.vy;
      p.alpha = Math.max(0, p.life / 60);
      p.life -= 1;
    });
    state.particles = state.particles.filter(p => p.life > 0);

    // If Wave Intro
    if (state.waveState === 'intro') {
      state.waveTransitionTimer -= 1;
      if (state.waveTransitionTimer <= 0) {
        state.waveState = 'playing';
      }
      return; // Skip spawning and enemy progression during intro banner
    }

    // Spawning Enemies (Authoritative Host generates spawns in co-op)
    const isHost = !isMultiplayer || (players.find(p => p.socketId === socket?.id)?.isHost);
    
    if (isHost && state.waveState === 'playing') {
      const now = Date.now();
      const spawnInterval = Math.max(1200, 3200 - state.wave * 150); // Spawning speed scales up
      
      if (now - state.lastSpawnTime > spawnInterval && state.waveSpawnedCount < state.waveTotalToSpawn) {
        spawnNewEnemyWave();
        state.lastSpawnTime = now;
      }

      // Check if all wave enemies spawned and cleared
      if (state.waveSpawnedCount >= state.waveTotalToSpawn && state.enemies.length === 0 && state.bullets.length === 0) {
        // Trigger Boss Fight on wave 5, 10, 15...
        if (state.wave % 5 === 0) {
          triggerBossWarning();
        } else {
          // Go to next wave
          advanceNextWave();
        }
      }
    }

    // Boss Phase Spawner
    if (isHost && state.waveState === 'boss_fight' && state.bossObj) {
      const boss = state.bossObj;
      boss.shootTimer -= 1;
      
      if (boss.shootTimer <= 0) {
        // Shoot single letter bullets or colored minions
        const isMinion = Math.random() < 0.4;
        if (isMinion) {
          spawnBossMinions();
        } else {
          fireBossBullet();
        }
        boss.shootTimer = Math.max(60, 160 - state.wave * 10);
      }
    }

    // Enemies movement
    const baseSpeedMultiplier = 1.0 + (state.wave * 0.08); // Speed scales up with waves
    const multiplayerDifficulty = isMultiplayer ? 1.25 : 1.0; // 25% harder as requested
    
    state.enemies.forEach(enemy => {
      enemy.y += enemy.speed * baseSpeedMultiplier * multiplayerDifficulty;
      
      // Elite/interceptor weaving logic
      if (enemy.type === 'interceptor') {
        enemy.x += Math.sin(enemy.y * 0.02) * 2;
      }

      // Cruiser shooting bullets logic
      if (enemy.type === 'cruiser' && isHost) {
        enemy.shootCooldown = (enemy.shootCooldown || 180) - 1;
        if (enemy.shootCooldown <= 0) {
          fireGeneralBullet(enemy);
          enemy.shootCooldown = 180 + Math.random() * 120;
        }
      }

      // Collision check with bottom border
      const thresholdY = canvas.height - 120;
      if (enemy.y >= thresholdY) {
        // Damage player
        takeDamage(20);
        // Destroy enemy
        state.enemies = state.enemies.filter(e => e.id !== enemy.id);
        handleEnemyCompletion(enemy.id);
        if (state.activeWordId === enemy.id) state.activeWordId = null;
        createExplosion(enemy.x, enemy.y, '#ff3366', 20, true);
        GameAudio.play('explosionLarge');
      }
    });

    // Bullets movement
    state.bullets.forEach(bullet => {
      bullet.y += bullet.speed * baseSpeedMultiplier * multiplayerDifficulty;

      // Hit bottom check
      const thresholdY = canvas.height - 100;
      if (bullet.y >= thresholdY) {
        // Bullet hit a ship -> Instant Game Over as requested
        takeDamage(100); // Triggers death instantly
        state.bullets = state.bullets.filter(b => b.id !== bullet.id);
      }
    });
  };

  // Host spawns standard wave enemies
  const spawnNewEnemyWave = () => {
    const state = stateRef.current;
    const canvas = canvasRef.current;
    if (!canvas) return;

    const spawnCount = Math.min(
      Math.random() < 0.6 ? 1 : 2, 
      state.waveTotalToSpawn - state.waveSpawnedCount
    );

    const newEnemies = [];

    for (let i = 0; i < spawnCount; i++) {
      // Determine enemy class
      let type = 'drone';
      let speed = 0.5 + Math.random() * 0.3;
      let hp = 1;
      
      const rng = Math.random();
      if (state.wave >= 2 && rng > 0.75) {
        type = 'interceptor'; // Elite
        speed = 0.9 + Math.random() * 0.4;
      } else if (state.wave >= 4 && rng > 0.90) {
        type = 'cruiser'; // General
        speed = 0.3 + Math.random() * 0.2;
        hp = 2;
      }

      const word = getRandomWordForWave(state.wave);
      const enemyId = Math.random().toString(36).substring(2, 9);
      
      // Determine spawn column (keep within central 60% of screen)
      const x = canvas.width * 0.25 + Math.random() * (canvas.width * 0.5);
      
      // In co-op, assign player color targets
      let color = shipColor;
      if (isMultiplayer && players && players.length > 0) {
        const colors = players.map(p => p.color).filter(Boolean);
        color = colors[Math.floor(Math.random() * colors.length)] || shipColor;
      }

      const enemy = {
        id: enemyId,
        word,
        color,
        x,
        y: -30,
        speed,
        targetIndex: 0,
        type,
        shootCooldown: 150
      };

      state.enemies.push(enemy);
      newEnemies.push(enemy);
      state.waveSpawnedCount += 1;
    }

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'SPAWN_ENEMIES',
        enemies: newEnemies,
        hostId: socket.id
      }));
    }
  };

  // Host fires bullets from general cruiser
  const fireGeneralBullet = (cruiser) => {
    const state = stateRef.current;
    const bulletId = Math.random().toString(36).substring(2, 9);
    // Random single letter
    const alphabet = 'abcdefghijklmnopqrstuvwxyz';
    const letter = alphabet[Math.floor(Math.random() * alphabet.length)];

    const bullet = {
      id: bulletId,
      letter,
      x: cruiser.x,
      y: cruiser.y + 15,
      speed: 1.5
    };

    state.bullets.push(bullet);

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'SPAWN_BULLET',
        bullet,
        hostId: socket.id
      }));
    }
  };

  // Boss Warning Cutscene triggers
  const triggerBossWarning = () => {
    const state = stateRef.current;
    state.waveState = 'boss_warning';
    state.waveTransitionTimer = 180; // Warning screen countdown
    state.targetNebulaColor = { h: 0, s: 70, l: 8 }; // Dark red glow background
    
    // Spawn warnings siren loop or flash triggers
    GameAudio.play('emp');

    setTimeout(() => {
      if (state.isLocalGameOver) return;
      spawnBossFight();
    }, 3000);
  };

  // Spawn Boss logic
  const spawnBossFight = () => {
    const state = stateRef.current;
    const canvas = canvasRef.current;
    if (!canvas) return;

    // Generate boss sequence words
    // Co-op boss contains cycling colored words
    let bossWords = [];
    if (isMultiplayer && players) {
      const colors = players.map(p => p.color).filter(Boolean);
      // Spawn 6 words, cycling through active player colors
      for (let i = 0; i < 6; i++) {
        const c = colors[i % colors.length];
        bossWords.push({
          id: `boss-w-${i}`,
          word: getRandomWord(7 + Math.floor(i / 2)),
          color: c,
          active: i === 0, // Only 1st word active initially
          targetIndex: 0
        });
      }
    } else {
      // Solo mode: standard 4 shield words
      for (let i = 0; i < 4; i++) {
        bossWords.push({
          id: `boss-w-${i}`,
          word: getRandomWord(6 + i),
          color: shipColor,
          active: i === 0,
          targetIndex: 0
        });
      }
    }

    state.waveState = 'boss_fight';
    state.bossObj = {
      id: 'boss',
      x: canvas.width / 2,
      y: 120,
      width: 180,
      height: 100,
      health: 100,
      maxHealth: 100,
      words: bossWords,
      phase: 0,
      shootTimer: 100
    };

    // Load boss words into the active gameplay targets
    // For clients, we push these words to the active enemies list
    loadBossWordsAsEnemies(bossWords);

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'SYNC_BOSS_PHASE',
        phase: 0,
        bossWords: bossWords,
        hostId: socket.id
      }));
    }
  };

  const loadBossWordsAsEnemies = (bossWords) => {
    const state = stateRef.current;
    const canvas = canvasRef.current;
    if (!canvas) return;

    // Add active boss word into standard enemy typing loop
    const activeWord = bossWords.find(w => w.active);
    if (activeWord) {
      const bossEnemy = {
        id: activeWord.id,
        word: activeWord.word,
        color: activeWord.color,
        x: canvas.width / 2,
        y: 180,
        speed: 0,
        targetIndex: 0,
        type: 'boss_shield'
      };
      // Insert to head of list
      state.enemies = [bossEnemy, ...state.enemies];
    }
  };

  // Boss fires single-letter bullet
  const fireBossBullet = () => {
    const state = stateRef.current;
    if (!state.bossObj) return;

    const bulletId = Math.random().toString(36).substring(2, 9);
    const alphabet = 'abcdefghijklmnopqrstuvwxyz';
    const letter = alphabet[Math.floor(Math.random() * alphabet.length)];

    // Target a player position randomly
    const targetPos = isMultiplayer && players.length > 0
      ? players[Math.floor(Math.random() * players.length)].position
      : 'center';
    
    const destX = getShipX(targetPos, window.innerWidth);

    // Calculate bullet velocities to shoot towards ship
    const startX = state.bossObj.x;
    const startY = state.bossObj.y + 40;
    const angle = Math.atan2(window.innerHeight - 80 - startY, destX - startX);

    const bullet = {
      id: bulletId,
      letter,
      x: startX,
      y: startY,
      speed: 1.8,
      vx: Math.cos(angle) * 2,
      vy: Math.sin(angle) * 2
    };

    state.bullets.push(bullet);

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'SPAWN_BULLET',
        bullet,
        hostId: socket.id
      }));
    }
  };

  // Boss spawns normal colored minions
  const spawnBossMinions = () => {
    const state = stateRef.current;
    const canvas = canvasRef.current;
    if (!canvas || !state.bossObj) return;

    const word = getRandomWord(4);
    const id = Math.random().toString(36).substring(2, 9);
    const spawnLeft = Math.random() < 0.5;
    const x = spawnLeft ? state.bossObj.x - 80 : state.bossObj.x + 80;

    let color = shipColor;
    if (isMultiplayer && players) {
      const colors = players.map(p => p.color).filter(Boolean);
      color = colors[Math.floor(Math.random() * colors.length)] || shipColor;
    }

    const minion = {
      id,
      word,
      color,
      x,
      y: state.bossObj.y + 40,
      speed: 0.7,
      targetIndex: 0,
      type: 'drone'
    };

    state.enemies.push(minion);

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'SPAWN_ENEMIES',
        enemies: [minion],
        hostId: socket.id
      }));
    }
  };

  // Co-op gameplay: take damage
  const takeDamage = (amount) => {
    const state = stateRef.current;
    state.health = Math.max(0, state.health - amount);
    state.screenShake = 12;
    state.flashFrame = 4;
    GameAudio.play('explosionPlayer');

    setHudState(prev => ({ ...prev, health: state.health }));

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'PLAYER_HIT',
        playerId: socket.id,
        health: state.health
      }));
    }

    // Check game over
    if (state.health <= 0) {
      if (isMultiplayer && socket) {
        socket.send(JSON.stringify({
          type: 'GAME_OVER',
          finalScore: state.score,
          waveReached: state.wave
        }));
      } else {
        triggerGameOver(state.score, state.wave);
      }
    }
  };

  const triggerGameOver = (finalScore, waveReached) => {
    const state = stateRef.current;
    state.isLocalGameOver = true;
    GameAudio.stopMusic();
    GameAudio.play('explosionPlayer');
    
    // Add giant player ship destruction particle burst
    const canvas = canvasRef.current;
    if (canvas) {
      const x = canvas.width / 2;
      const y = canvas.height - 80;
      createExplosion(x, y, '#ff1111', 40, true);
    }

    setTimeout(() => {
      onGameOver(finalScore, waveReached);
    }, 1500);
  };

  // Advance level/wave
  const advanceNextWave = () => {
    const state = stateRef.current;
    const nextWaveNum = state.wave + 1;
    
    state.wave = nextWaveNum;
    state.waveState = 'intro';
    state.waveTransitionTimer = 180;
    state.enemies = [];
    state.bullets = [];
    state.waveSpawnedCount = 0;
    state.waveTotalToSpawn = 10 + nextWaveNum * 4;
    
    state.targetNebulaColor = {
      h: (260 + nextWaveNum * 30) % 360,
      s: 60,
      l: 8 + (nextWaveNum % 4)
    };

    setHudState(prev => ({ ...prev, wave: nextWaveNum }));
    
    // Play wave start audio
    GameAudio.play('emp');

    if (isMultiplayer && socket) {
      socket.send(JSON.stringify({
        type: 'NEXT_WAVE',
        wave: nextWaveNum
      }));
    }
  };

  // Tick boss shield logic when active word dies
  // In the update loop we monitor boss words completion
  const checkBossShieldsCompleted = (completedEnemyId) => {
    const state = stateRef.current;
    if (state.waveState !== 'boss_fight' || !state.bossObj) return;

    const boss = state.bossObj;
    const shieldIndex = boss.words.findIndex(w => w.id === completedEnemyId);
    
    if (shieldIndex !== -1) {
      // Mark shield word complete
      boss.words[shieldIndex].active = false;
      boss.words[shieldIndex].completed = true;

      // Update boss general health percentage
      const completedCount = boss.words.filter(w => w.completed).length;
      boss.health = Math.round(100 - (completedCount / boss.words.length) * 100);

      // Spark massive explosion on the boss itself
      createExplosion(boss.x, boss.y, `var(--neon-${boss.words[shieldIndex].color})`, 30, true);

      // Check if all boss words completed
      if (completedCount >= boss.words.length) {
        // Boss destroyed!
        createExplosion(boss.x, boss.y, '#ffffff', 80, true);
        GameAudio.play('explosionLarge');
        state.bossObj = null;
        
        // Wait, clear all remaining minions/bullets
        state.enemies = [];
        state.bullets = [];
        
        // Advance wave
        setTimeout(() => {
          advanceNextWave();
        }, 1500);
      } else {
        // Activate next word in cycle pattern
        const nextActive = boss.words.find(w => !w.completed);
        if (nextActive) {
          nextActive.active = true;
          loadBossWordsAsEnemies(boss.words);
          
          if (isMultiplayer && socket) {
            socket.send(JSON.stringify({
              type: 'SYNC_BOSS_PHASE',
              phase: boss.phase + 1,
              bossWords: boss.words,
              hostId: socket.id
            }));
          }
        }
      }
    }
  };

  // Core Canvas Drawing System
  const drawGame = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const state = stateRef.current;

    // Apply Screen Shake
    ctx.save();
    if (state.screenShake > 0.5) {
      const dx = (Math.random() - 0.5) * state.screenShake;
      const dy = (Math.random() - 0.5) * state.screenShake;
      ctx.translate(dx, dy);
    }

    // Clear Canvas with glowing nebula gradient
    ctx.fillStyle = `hsl(${state.nebulaColor.h}, ${state.nebulaColor.s}%, ${state.nebulaColor.l}%)`;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw deep background star grid
    ctx.strokeStyle = `rgba(255, 255, 255, 0.025)`;
    ctx.lineWidth = 1.0;
    const gridSize = 100;
    const offset = (state.waveTransitionTimer * 0.1) % gridSize; // Grid moves slightly
    
    for (let x = 0; x < canvas.width; x += gridSize) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, canvas.height);
      ctx.stroke();
    }
    for (let y = 0; y < canvas.height; y += gridSize) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(canvas.width, y);
      ctx.stroke();
    }

    // Draw Parallax Scenery (broken towers, asteroids, planets on margins)
    state.scenery.forEach(item => {
      ctx.save();
      ctx.translate(item.x, item.y);
      ctx.rotate(item.rotation);
      ctx.strokeStyle = item.color;
      ctx.lineWidth = 1.5;

      if (item.type === 'asteroid') {
        // Draw irregular polygon
        ctx.beginPath();
        const pts = 8;
        for (let j = 0; j < pts; j++) {
          const angle = (j / pts) * Math.PI * 2;
          const r = item.size * (0.8 + Math.random() * 0.3);
          const px = Math.cos(angle) * r;
          const py = Math.sin(angle) * r;
          if (j === 0) ctx.moveTo(px, py);
          else ctx.lineTo(px, py);
        }
        ctx.closePath();
        ctx.stroke();
      } else if (item.type === 'tower') {
        // Draw broken girder space-tower outline
        ctx.beginPath();
        const halfSize = item.size / 2;
        ctx.rect(-halfSize, -item.size, item.size, item.size * 2);
        // Draw crossed bracing girders
        ctx.moveTo(-halfSize, -item.size);
        ctx.lineTo(halfSize, item.size * 1);
        ctx.moveTo(halfSize, -item.size);
        ctx.lineTo(-halfSize, item.size * 1);
        ctx.stroke();
      } else if (item.type === 'planet') {
        // Draw wireframe planet sphere
        ctx.beginPath();
        ctx.arc(0, 0, item.size, 0, Math.PI * 2);
        ctx.stroke();
        // Draw equator orbit line
        ctx.beginPath();
        ctx.ellipse(0, 0, item.size * 1.4, item.size * 0.3, Math.PI / 8, 0, Math.PI * 2);
        ctx.stroke();
      }
      ctx.restore();
    });

    // Draw active particle clouds
    state.particles.forEach(p => {
      ctx.save();
      ctx.globalAlpha = p.alpha;
      ctx.fillStyle = p.color;
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
      ctx.fill();
      ctx.restore();
    });

    // Draw Lasers
    state.lasers.forEach(laser => {
      ctx.save();
      ctx.shadowBlur = 10;
      ctx.shadowColor = laser.color;
      ctx.strokeStyle = laser.color;
      ctx.globalAlpha = laser.alpha;
      ctx.lineWidth = 3.0;

      ctx.beginPath();
      ctx.moveTo(laser.fromX, laser.fromY);
      ctx.lineTo(laser.toX, laser.toY);
      ctx.stroke();
      ctx.restore();
    });

    // Draw Boss
    if (state.waveState === 'boss_fight' && state.bossObj) {
      const boss = state.bossObj;
      ctx.save();
      ctx.translate(boss.x, boss.y);
      ctx.shadowBlur = 15;
      ctx.shadowColor = 'var(--neon-purple)';
      ctx.strokeStyle = 'var(--neon-purple)';
      ctx.lineWidth = 3.0;

      // Draw massive procedural boss command fortress
      ctx.beginPath();
      ctx.moveTo(-boss.width / 2, -boss.height / 2);
      ctx.lineTo(boss.width / 2, -boss.height / 2);
      ctx.lineTo(boss.width * 0.4, boss.height / 2);
      ctx.lineTo(boss.width * 0.15, boss.height * 0.3);
      ctx.lineTo(-boss.width * 0.15, boss.height * 0.3);
      ctx.lineTo(-boss.width * 0.4, boss.height / 2);
      ctx.closePath();
      ctx.stroke();

      // Draw boss health bar
      const barW = 200;
      const barH = 6;
      ctx.fillStyle = 'rgba(255, 255, 255, 0.1)';
      ctx.fillRect(-barW / 2, -boss.height / 2 - 25, barW, barH);
      ctx.fillStyle = 'var(--neon-purple)';
      ctx.fillRect(-barW / 2, -boss.height / 2 - 25, barW * (boss.health / 100), barH);

      // Label "BOSS"
      ctx.fillStyle = '#ffffff';
      ctx.font = '700 12px var(--font-display)';
      ctx.textAlign = 'center';
      ctx.fillText('COMMAND DREADNOUGHT', 0, -boss.height / 2 - 35);

      ctx.restore();
    }

    // Draw Enemies (Descending ships with words)
    state.enemies.forEach(enemy => {
      ctx.save();
      ctx.translate(enemy.x, enemy.y);
      ctx.shadowBlur = 8;
      ctx.shadowColor = `var(--neon-${enemy.color})`;
      ctx.strokeStyle = `var(--neon-${enemy.color})`;
      ctx.lineWidth = 2.0;

      // Draw procedural enemy design based on class
      ctx.beginPath();
      if (enemy.type === 'interceptor') {
        // Slick forward sweep design
        ctx.moveTo(0, 15);
        ctx.lineTo(12, -8);
        ctx.lineTo(6, -2);
        ctx.lineTo(-6, -2);
        ctx.lineTo(-12, -8);
      } else if (enemy.type === 'cruiser') {
        // Bulky tank shape
        ctx.moveTo(0, 20);
        ctx.lineTo(16, 5);
        ctx.lineTo(12, -15);
        ctx.lineTo(-12, -15);
        ctx.lineTo(-16, 5);
      } else {
        // Standard drone (small triangle)
        ctx.moveTo(0, 10);
        ctx.lineTo(8, -8);
        ctx.lineTo(0, -4);
        ctx.lineTo(-8, -8);
      }
      ctx.closePath();
      ctx.stroke();

      ctx.restore();

      // Draw text word label centered above the ship
      ctx.save();
      const isTargeted = state.activeWordId === enemy.id;
      ctx.font = isTargeted ? '700 15px var(--font-display)' : '400 14px var(--font-body)';
      ctx.textAlign = 'center';

      const word = enemy.word;
      const progressIndex = enemy.targetIndex;

      // Draw glow behind active letters
      if (isTargeted) {
        ctx.shadowBlur = 10;
        ctx.shadowColor = `var(--neon-${enemy.color})`;
      }

      // Draw typed letters (dim/gray or glowing) and untyped letters
      const wordWidth = ctx.measureText(word).width;
      const startX = enemy.x - wordWidth / 2;

      ctx.textBaseline = 'bottom';
      let currentX = startX;

      for (let i = 0; i < word.length; i++) {
        const char = word[i];
        const hasTyped = i < progressIndex;

        if (hasTyped) {
          ctx.fillStyle = 'rgba(255, 255, 255, 0.25)'; // Typed letters dimmed
        } else {
          ctx.fillStyle = `var(--neon-${enemy.color})`; // Target color for active letters
        }
        
        ctx.fillText(char, currentX + ctx.measureText(char).width / 2, enemy.y - 18);
        currentX += ctx.measureText(char).width;
      }

      ctx.restore();
    });

    // Draw single-character bullets (white)
    state.bullets.forEach(bullet => {
      ctx.save();
      ctx.translate(bullet.x, bullet.y);
      ctx.shadowBlur = 8;
      ctx.shadowColor = '#ffffff';
      ctx.strokeStyle = '#ffffff';
      ctx.lineWidth = 1.5;

      // Small glowing circle containing the single letter
      ctx.beginPath();
      ctx.arc(0, 0, 10, 0, Math.PI * 2);
      ctx.stroke();
      
      ctx.fillStyle = '#ffffff';
      ctx.font = '700 12px var(--font-display)';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(bullet.letter.toUpperCase(), 0, 0);

      ctx.restore();

      // If bullet has velocity velocities, update them
      if (bullet.vx !== undefined && bullet.vy !== undefined) {
        bullet.x += bullet.vx;
        bullet.y += bullet.vy;
      }
    });

    // Draw Player Ship(s)
    const localPosition = isMultiplayer 
      ? players.find(p => p.socketId === socket?.id)?.position || 'center' 
      : 'center';

    const renderShip = (x, y, color, labelText) => {
      ctx.save();
      ctx.translate(x, y);
      ctx.shadowBlur = 10;
      ctx.shadowColor = `var(--neon-${color})`;
      ctx.strokeStyle = `var(--neon-${color})`;
      ctx.lineWidth = 2.5;

      // Draw procedural futuristic ship shape
      ctx.beginPath();
      ctx.moveTo(0, -20);
      ctx.lineTo(15, 12);
      ctx.lineTo(0, 5);
      ctx.lineTo(-15, 12);
      ctx.closePath();
      ctx.stroke();

      // Draw thruster fire particles procedurally
      ctx.fillStyle = `rgba(${color === 'red' ? '255, 51, 102' : color === 'blue' ? '51, 204, 255' : '57, 255, 20'}, 0.3)`;
      ctx.beginPath();
      ctx.moveTo(-6, 7);
      ctx.lineTo(0, 7 + Math.random() * 15);
      ctx.lineTo(6, 7);
      ctx.closePath();
      ctx.fill();

      // Draw username under the ship small
      ctx.fillStyle = '#8a8fa3';
      ctx.font = '400 11px var(--font-body)';
      ctx.textAlign = 'center';
      ctx.fillText(labelText, 0, 30);

      ctx.restore();
    };

    if (isMultiplayer && players) {
      // Draw all active teammates in co-op
      players.forEach(p => {
        const sx = getShipX(p.position, canvas.width);
        const sy = canvas.height - 80;
        
        // Draw only if player has not died
        const mateState = state.teammates.find(m => m.socketId === p.socketId);
        if (!mateState || mateState.health > 0) {
          const suffix = p.socketId === socket?.id ? ' (You)' : '';
          renderShip(sx, sy, p.color || shipColor, p.username + suffix);
        }
      });
    } else {
      // Draw single solo player ship
      renderShip(canvas.width / 2, canvas.height - 80, shipColor, username + ' (You)');
    }

    // Cutscenes & Banners (e.g. Wave transitions)
    if (state.waveState === 'intro') {
      ctx.save();
      // Sliding background grid flash
      ctx.fillStyle = 'rgba(255, 255, 255, 0.02)';
      ctx.fillRect(0, canvas.height * 0.35, canvas.width, canvas.height * 0.3);
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.1)';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(0, canvas.height * 0.35);
      ctx.lineTo(canvas.width, canvas.height * 0.35);
      ctx.moveTo(0, canvas.height * 0.65);
      ctx.lineTo(canvas.width, canvas.height * 0.65);
      ctx.stroke();

      // Main Text
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      
      // Flash title
      ctx.fillStyle = '#ffffff';
      ctx.font = '900 3rem var(--font-display)';
      ctx.fillText(`WAVE ${state.wave}`, canvas.width / 2, canvas.height * 0.46);

      ctx.fillStyle = 'var(--neon-blue)';
      ctx.font = '400 1rem var(--font-body)';
      ctx.fillText('INCOMING HOSTILE ATTACKS - PREPARE KEYBOARD', canvas.width / 2, canvas.height * 0.54);

      ctx.restore();
    } else if (state.waveState === 'boss_warning') {
      ctx.save();
      // Blinking red alert screen
      const alpha = Math.abs(Math.sin(state.waveTransitionTimer * 0.08)) * 0.2;
      ctx.fillStyle = `rgba(255, 0, 0, ${alpha})`;
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      ctx.fillStyle = 'rgba(255, 0, 0, 0.05)';
      ctx.fillRect(0, canvas.height * 0.35, canvas.width, canvas.height * 0.3);

      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      
      ctx.fillStyle = 'var(--neon-red)';
      ctx.font = '900 3.2rem var(--font-display)';
      ctx.fillText(`WARNING`, canvas.width / 2, canvas.height * 0.45);
      
      ctx.fillStyle = '#ffffff';
      ctx.font = '600 1.2rem var(--font-body)';
      ctx.fillText(`BOSS DREADNOUGHT APPROACHING`, canvas.width / 2, canvas.height * 0.55);

      ctx.restore();
    }

    // Draw Impact Frame Flash (brief screen invert color flash on hits)
    if (state.flashFrame > 0) {
      ctx.fillStyle = `rgba(255, 255, 255, ${state.flashFrame * 0.15})`;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
    }

    ctx.restore(); // Pop Screen Shake
  };

  // Check if target was boss shield
  const handleEnemyCompletion = (enemyId) => {
    // If it is a boss shield word
    if (enemyId.startsWith('boss-w-')) {
      checkBossShieldsCompleted(enemyId);
    }
  };

  return (
    <div 
      className="game-screen" 
      onClick={() => canvasRef.current && canvasRef.current.focus()}
    >
      <canvas
        id="gameCanvas"
        ref={canvasRef}
        tabIndex="0"
        onKeyDown={handleKeyDown}
      />
      <GameHUD
        score={hudState.score}
        multiplier={hudState.multiplier}
        wave={hudState.wave}
        isMultiplayer={isMultiplayer}
        teamPlayers={hudState.teammates}
      />
    </div>
  );
}
